# Generated by Django 2.2.5 on 2023-12-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instan_book',
            new_name='instant_book',
        ),
    ]
