# Generated by Django 2.2.5 on 2023-12-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20231212_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(),
        ),
    ]
