# Generated by Django 2.2.5 on 2024-01-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20231215_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(verbose_name='How many people will be staying?'),
        ),
    ]
