# Generated by Django 2.2.5 on 2023-12-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStampedModel',
        ),
    ]
