# Generated by Django 2.2.5 on 2023-12-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='room_field',
            new_name='room',
        ),
    ]
